const {chromium}=require('playwright');
const {loadState}=require('./auth');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const ctx=await browser.newContext({storageState:loadState('quarterfull')});
 const page=await ctx.newPage();
 await page.goto('https://quarterfull.io/studio-cursor',{waitUntil:'domcontentloaded',timeout:60000});
 await page.waitForTimeout(3000);
 const projectNode=page.getByText('새 작품',{exact:true}).last();
 if(await projectNode.count()&&await projectNode.isVisible()){await projectNode.click();await page.waitForTimeout(700);}
 const episodePath=page.getByText('/원고(출간용)/1화',{exact:true}).first();
 if(!(await episodePath.count())) throw new Error('SAFETY: new project episode path missing');
 await episodePath.click(); await page.waitForTimeout(700);
 const header=page.getByText('새 작품 · 1화',{exact:false}).first();
 if(!(await header.count())) throw new Error('SAFETY: new project episode 1 header missing');
 const editor=page.locator('[contenteditable=true].ProseMirror').first();
 const editorText=(await editor.innerText()).replace(/\u00a0/g,' ');
 if(!editorText.includes('알람이 울리기도 전에 눈이 먼저 뜨였다.') || !editorText.includes('평생을 바쳐 갚아야 할 빚을 직접 걸었지.')) throw new Error('SAFETY: frozen chapter 1 body incomplete');
 const prep=page.getByRole('button',{name:'출간 준비'}).first(); await prep.click(); await page.waitForTimeout(1000);
 const dialog=page.locator('[role=dialog]').last();
 if(!(await dialog.count()) || !(await dialog.innerText()).includes('작품 관리')) throw new Error('management dialog missing');
 const titleInput=dialog.locator('input[placeholder="작품 제목을 입력해 주세요."]');
 await titleInput.fill('자정 이후의 콜센터');
 await dialog.getByRole('button',{name:'작품 제목 저장'}).click();
 await page.waitForTimeout(1200);
 const genre=dialog.getByRole('button',{name:'공포/추리',exact:true});
 if(await genre.count()){await genre.click();await page.waitForTimeout(700);}
 const intro='빚 8천만 원에 짓눌린 야간 상담원 강이현. 자정 이후 7번 단말기에 걸려오는 비정상적인 전화는 현실의 죽음과 연결되고, 통화를 해결할 때마다 그의 빚이 실제로 사라진다. 그런데 어느 날, 발신자 이름에 자신의 이름이 뜬다.';
 const introBox=dialog.locator('textarea[placeholder="독자에게 보일 작품 소개를 적어주세요."]');
 await introBox.fill(intro);
 const introSave=dialog.getByRole('button',{name:'소개글 저장'});
 if(await introSave.isEnabled()) await introSave.click();
 await page.waitForTimeout(1200);
 const body=(await dialog.innerText());
 const savedTitle=await titleInput.inputValue();
 const savedIntro=await introBox.inputValue();
 if(savedTitle!=='자정 이후의 콜센터') throw new Error('title readback mismatch');
 if(savedIntro!==intro) throw new Error('intro readback mismatch');
 const report={phase:'metadata-configured',title:savedTitle,introExact:savedIntro===intro,genreVisible:body.includes('공포/추리'),status:body.includes('미출간')?'미출간':'unknown',publishControls:await dialog.getByRole('button',{name:'출간',exact:true}).count(),body:body.slice(0,5000)};
 fs.mkdirSync('reports',{recursive:true});fs.writeFileSync('reports/quarterfull-project-probe.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
