const {chromium}=require('playwright');
const {loadState}=require('./auth');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const ctx=await browser.newContext({storageState:loadState('quarterfull')});
 const page=await ctx.newPage();
 await page.goto('https://quarterfull.io/studio-cursor',{waitUntil:'domcontentloaded',timeout:60000});
 await page.waitForTimeout(3500);
 const title='자정 이후의 콜센터';
 const titleNode=page.getByText(title,{exact:true}).first();
 if(!(await titleNode.count())) throw new Error('SAFETY: published target title missing');
 const info=await titleNode.evaluate(el=>{let p=el;for(let i=0;i<8&&p;i++,p=p.parentElement){const t=(p.innerText||'').trim();if(t.includes('출간')&&t.includes('자정 이후의 콜센터')) return {tag:p.tagName,cls:p.className,text:t.slice(0,1000),html:p.outerHTML.slice(0,4000)};}return null;});
 await titleNode.click();
 await page.waitForTimeout(1800);
 const body=(await page.locator('body').innerText()).slice(0,30000);
 const controls=await page.locator('button,[role=button],a').evaluateAll(es=>es.map((e,i)=>({i,text:(e.innerText||'').trim(),aria:e.getAttribute('aria-label'),title:e.getAttribute('title'),href:e.getAttribute('href'),disabled:!!e.disabled})).filter(x=>x.text||x.aria||x.title));
 const editors=await page.locator('[contenteditable=true].ProseMirror').evaluateAll(es=>es.map(e=>(e.innerText||'').slice(0,2000)));
 const report={phase:'target-project-selected',url:page.url(),cardAncestor:info,body,controls,editors};
 fs.mkdirSync('reports',{recursive:true});fs.writeFileSync('reports/quarterfull-project-probe.json',JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
