const {chromium}=require('playwright');
const {loadState,persistState}=require('./auth');
const fs=require('fs');
const TARGET='자정 이후의 콜센터';
const trigger=fs.readFileSync('quarterfull-upload-trigger.txt','utf8');
let episodes=[]; let m=trigger.match(/episodes?\s+(\d+)\s*-\s*(\d+)/i);
if(m){for(let n=Number(m[1]);n<=Number(m[2]);n++)episodes.push(n);}else{m=trigger.match(/episode\s+(\d+)/i);if(m)episodes=[Number(m[1])];}
if(!episodes.length||episodes.some(n=>n<3||n>10))throw new Error('EPISODE_TRIGGER_INVALID');
const norm=s=>s.replace(/\s+/g,'');
function loadEpisode(ep){const body=fs.readFileSync(`../books/live-gemini-pilot/commercial/chapter-${ep}.md`,'utf8').trim();const q=JSON.parse(fs.readFileSync(`../books/live-gemini-pilot/commercial/chapter-${ep}-quality.json`,'utf8'));if(q.gate!=='PASS'||q.lexical_preflight!=='PASS'||q.independent_reviewer!=='PASS'||q.continuity_reviewer!=='PASS'||(q.issues||[]).length)throw new Error(`QUALITY_GATE_BLOCK:${ep}`);return body;}
async function ensureTarget(page){await page.goto('https://quarterfull.io/studio-cursor',{waitUntil:'domcontentloaded',timeout:60000});await page.waitForTimeout(4000);let root=await page.locator('body').innerText();if(!root.includes(TARGET))throw new Error('TARGET_PROJECT_NOT_VISIBLE:'+TARGET);if(!root.includes('작업 중: '+TARGET)){const projects=page.getByText(TARGET,{exact:true});let p=null;for(let i=0;i<await projects.count();i++){if(await projects.nth(i).isVisible()){p=projects.nth(i);break;}}if(!p)p=projects.first();await p.click({force:true});await page.waitForTimeout(2500);}if(!(await page.locator('body').innerText()).includes('작업 중: '+TARGET))throw new Error('TARGET_PROJECT_NOT_SELECTED');}
async function chooseEpisode(page,label){const nodes=page.getByText(label,{exact:true});let fallback=null;for(let i=0;i<await nodes.count();i++){const n=nodes.nth(i);const chain=await n.evaluate(e=>{let s='',p=e;for(let k=0;k<7&&p;k++,p=p.parentElement)s+=' '+(p.textContent||'');return s.slice(0,5000);});if(chain.includes(`/원고(출간용)/${label}`)){if(await n.isVisible())return n;if(!fallback)fallback=n;}}return fallback;}
async function waitForDocPath(page,label,timeout=30000){const path=`/원고(출간용)/${label}`,end=Date.now()+timeout;while(Date.now()<end){if((await page.locator('body').innerText()).includes(path)){const n=await chooseEpisode(page,label);if(n)return n;}await page.waitForTimeout(1000);}return null;}
async function ensureDoc(page,ep){const label=`${ep}화`;let node=await waitForDocPath(page,label,3000);if(node)return node;const ai=page.locator('textarea[placeholder="무엇을 만들고 싶은지 말해주세요."]');if(await ai.count()===0)throw new Error(`AI_COMMAND_BOX_NOT_FOUND:${ep}`);await ai.fill(`현재 작업 중인 작품 ${TARGET}에서 기존 회차는 절대 수정하지 말고, 원고(출간용) 폴더 아래에 새 문서 ${label}를 생성만 해줘. ${label} 본문은 작성하거나 수정하지 마.`);const send=page.locator('button[aria-label="전송"]');await page.waitForFunction(()=>{const b=document.querySelector('button[aria-label="전송"]');return b&&!b.disabled;},{timeout:5000});await send.click();node=await waitForDocPath(page,label,35000);if(!node)throw new Error(`EPISODE_CREATE_FAILED:${label}`);return node;}
async function activateEpisode(page,node,label){const editor=page.locator('div.tiptap.ProseMirror[contenteditable="true"]');for(let attempt=1;attempt<=4;attempt++){try{if(await node.isVisible())await node.click({force:true});else await node.evaluate(e=>e.dispatchEvent(new MouseEvent('click',{bubbles:true,cancelable:true,view:window})));}catch(e){}try{await editor.waitFor({state:'visible',timeout:15000});return editor.first();}catch(e){}await page.waitForTimeout(1500);node=await chooseEpisode(page,label)||node;}throw new Error(`EDITOR_NOT_FOUND_AFTER_RETRIES:${label}`);}
async function replaceAll(page,editor,body){await editor.click();await editor.evaluate((el,text)=>{el.focus();const sel=window.getSelection();const range=document.createRange();range.selectNodeContents(el);sel.removeAllRanges();sel.addRange(range);document.execCommand('insertText',false,text);},body);await page.waitForTimeout(2500);}
let browser=null,ctx=null;
(async()=>{browser=await chromium.launch({headless:true});ctx=await browser.newContext({storageState:loadState('quarterfull')});const page=await ctx.newPage();fs.mkdirSync('reports',{recursive:true});const results=[];for(const ep of episodes){await ensureTarget(page);const body=loadEpisode(ep),label=`${ep}화`;const node=await ensureDoc(page,ep);const editor=await activateEpisode(page,node,label);const current=await page.locator('body').innerText();if(!current.includes('작업 중: '+TARGET)||!current.includes(`/원고(출간용)/${label}`))throw new Error(`EPISODE_SELECTION_UNVERIFIED:${ep}`);await replaceAll(page,editor,body);let readback=(await editor.innerText()).trim();if(norm(readback)!==norm(body)){console.log(`FIRST_READBACK_MISMATCH:${ep}:${readback.length}:${body.length}`);await replaceAll(page,editor,body);readback=(await editor.innerText()).trim();}if(norm(readback)!==norm(body))throw new Error(`READBACK_MISMATCH:${ep}:${readback.length}:${body.length}`);await editor.press('End');await editor.press(' ');await editor.press('Backspace');await page.waitForTimeout(6000);const verified=norm((await editor.innerText()).trim())===norm(body);if(!verified)throw new Error(`FINAL_READBACK_MISMATCH:${ep}`);const r={platform:'quarterfull',episode:ep,target:TARGET,chars:body.length,verified,status:'DRAFT_SAVED_VERIFIED'};fs.writeFileSync(`reports/quarterfull-upload-${ep}.json`,JSON.stringify(r,null,2));results.push(r);console.log(JSON.stringify(r));}await persistState(ctx,'quarterfull');console.log('QF_AUTH_STATE_PERSISTED');console.log('BATCH_OK',JSON.stringify(results.map(x=>x.episode)));await browser.close();})().catch(async e=>{try{if(ctx){await persistState(ctx,'quarterfull');console.log('QF_AUTH_STATE_PERSISTED_AFTER_ERROR');}}catch{}try{if(browser)await browser.close();}catch{}console.error(e);process.exit(1);});
