const {chromium}=require('playwright');
const {loadState}=require('./auth');
const fs=require('fs');
(async()=>{
 const browser=await chromium.launch({headless:true});
 const ctx=await browser.newContext({storageState:loadState('quarterfull')});
 const page=await ctx.newPage();
 await page.goto('https://quarterfull.io/studio-cursor',{waitUntil:'domcontentloaded',timeout:60000}); await page.waitForTimeout(3500);
 const title=page.getByText('자정 이후의 콜센터',{exact:true}).first(); if(!(await title.count())) throw new Error('SAFETY target missing'); await title.click(); await page.waitForTimeout(1200);
 if(!(await page.locator('body').innerText()).includes('작업 중: 자정 이후의 콜센터')) throw new Error('SAFETY target not active');
 const ep1=page.getByText('/원고(출간용)/1화',{exact:true}).first(); if(!(await ep1.count())) throw new Error('SAFETY target ep1 path missing'); await ep1.click(); await page.waitForTimeout(1200);
 const editor=page.locator('[contenteditable=true].ProseMirror').first(); if(!(await editor.count())) throw new Error('SAFETY target editor missing');
 const editorText=await editor.innerText(); if(!editorText.includes('알람이 울리기도 전에 눈이 먼저 뜨였다.')) throw new Error('SAFETY wrong editor still active');
 const folder=page.getByText('/원고(출간용)',{exact:true}).first();
 const nearby=await folder.evaluate(el=>{let p=el;for(let i=0;i<6&&p;i++,p=p.parentElement){const t=(p.innerText||'').trim();if(t.includes('/원고(출간용)')) return {tag:p.tagName,cls:p.className,text:t.slice(0,1200),html:p.outerHTML.slice(0,7000)};}return null;});
 await folder.click(); await page.waitForTimeout(700);
 const controls=await page.locator('button,[role=button],a').evaluateAll(es=>es.map((e,i)=>({i,text:(e.innerText||'').trim(),aria:e.getAttribute('aria-label'),title:e.getAttribute('title'),disabled:!!e.disabled,html:e.outerHTML.slice(0,1200)})).filter(x=>x.text||x.aria||x.title));
 const body=(await page.locator('body').innerText()).slice(0,22000);
 const report={phase:'target-tree-inspection',url:page.url(),nearby,body,controls}; fs.mkdirSync('reports',{recursive:true}); fs.writeFileSync('reports/quarterfull-project-probe.json',JSON.stringify(report,null,2)); console.log(JSON.stringify(report,null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
