const {chromium}=require('playwright');
const {loadState}=require('./auth');
const fs=require('fs');
(async()=>{
 const body=fs.readFileSync('../books/live-gemini-pilot/commercial/chapter-1.md','utf8').trim();
 const browser=await chromium.launch({headless:true});
 const ctx=await browser.newContext({storageState:loadState('quarterfull')});
 const page=await ctx.newPage();
 await page.goto('https://quarterfull.io/studio-cursor',{waitUntil:'domcontentloaded',timeout:60000});
 await page.waitForTimeout(2000);
 const draft=page.getByRole('button',{name:/I already have a draft/i});
 await draft.first().click(); await page.waitForTimeout(800);
 const manuscript=page.locator('textarea[placeholder*="19,000"]');
 await manuscript.fill(body);
 const helper=page.locator('textarea').nth(1); if(await helper.count()) await helper.fill('이 원고를 그대로 새 작품의 첫 화 원고로 사용해 주세요. 원문을 임의로 재작성하지 마세요.');
 const start=page.getByRole('button',{name:/Start writing/i});
 const enabled=await start.isEnabled(); if(!enabled) throw new Error('START_STILL_DISABLED_AFTER_FILL');
 await start.click(); await page.waitForTimeout(6000);
 const controls=await page.evaluate(()=>[...document.querySelectorAll('input,textarea,select,button,a,[role=button],[contenteditable=true]')].map((e,i)=>({i,tag:e.tagName.toLowerCase(),type:e.getAttribute('type'),name:e.getAttribute('name'),id:e.id||null,href:e.getAttribute('href'),placeholder:e.getAttribute('placeholder'),aria:e.getAttribute('aria-label'),disabled:e.disabled||e.getAttribute('aria-disabled'),text:(e.innerText||e.value||'').replace(/\s+/g,' ').trim().slice(0,300),contenteditable:e.getAttribute('contenteditable')})).slice(0,500));
 const report={url:page.url(),title:await page.title(),body:(await page.locator('body').innerText()).slice(0,24000),controls};
 fs.mkdirSync('reports',{recursive:true}); fs.writeFileSync('reports/quarterfull-probe.json',JSON.stringify(report,null,2));
 console.log('QUARTERFULL_AFTER_START',report.url,'controls='+controls.length); console.log(JSON.stringify(report,null,2));
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
